"""Surface scan container plus point-cloud conversion and export.

A Gocator surface arrives as a **dense 2-D grid**, not an unordered cloud —
rows run along Y (the travel/gantry direction), columns along X (across the
laser line). Both message flavours carry the same raw-count-to-mm scaling:

    value_mm = offset_um / 1000 + resolution_nm / 1e6 * raw_count

Resolutions are nanometres (``k32u``), offsets micrometres (``k32s``), and
the raw grid values are 16-bit signed counts where ``0x8000`` (-32768) marks
an invalid/missing point. Confirmed against
``samples/C/ReceiveSurface/src/ReceiveSurface.c``.

For ``GO_DATA_MESSAGE_TYPE_UNIFORM_SURFACE`` only Z is transmitted per cell —
X and Y are implied by column/row index. For
``GO_DATA_MESSAGE_TYPE_SURFACE_POINT_CLOUD`` every cell carries its own
x/y/z raw triple, which is what an un-resampled surface needs.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np

NM_TO_MM = 1e-6
UM_TO_MM = 1e-3

#: Raw 16-bit sentinel for "no data" — see module docstring.
INVALID_RANGE_16BIT = -32768


@dataclass
class SurfaceScan:
    """One Gocator surface, in engineering units.

    Attributes:
        z_mm: (rows, cols) float array of heights in mm, with invalid points
            as NaN. Rows run along Y (travel), columns along X.
        x_mm: (cols,) column centre positions in mm, for a uniform surface;
            or (rows, cols) per-cell X values for an un-resampled point cloud.
        y_mm: (rows,) row positions in mm, or (rows, cols) for a point cloud.
        metadata: Acquisition context — message type, resolutions/offsets,
            configured travel speed, frame rate, timestamps, etc.
        is_uniform: True when built from a UNIFORM_SURFACE message (implied
            X/Y), False for a SURFACE_POINT_CLOUD message (explicit per-cell
            X/Y).
    """

    z_mm: np.ndarray
    x_mm: np.ndarray
    y_mm: np.ndarray
    metadata: Dict[str, Any] = field(default_factory=dict)
    is_uniform: bool = True

    # ------------------------------------------------------------------
    # Derived views
    # ------------------------------------------------------------------

    @property
    def shape(self) -> tuple:
        """(rows, cols) of the height grid."""
        return tuple(self.z_mm.shape)

    @property
    def valid_count(self) -> int:
        """Number of cells holding a real measurement (non-NaN)."""
        return int(np.count_nonzero(~np.isnan(self.z_mm)))

    def to_points(self, drop_invalid: bool = True) -> np.ndarray:
        """Flatten to an (N, 3) XYZ point cloud in mm.

        Args:
            drop_invalid: Drop points whose Z is NaN (no laser return).
                Keep them only if you specifically want a full-grid array.

        Returns:
            (N, 3) float array of [x, y, z] in mm.
        """
        if self.is_uniform:
            xx, yy = np.meshgrid(self.x_mm, self.y_mm)
        else:
            xx, yy = self.x_mm, self.y_mm

        points = np.column_stack(
            [xx.ravel(), yy.ravel(), self.z_mm.ravel()]
        )
        if drop_invalid:
            points = points[~np.isnan(points[:, 2])]
        return points

    # ------------------------------------------------------------------
    # Export
    # ------------------------------------------------------------------

    def save_csv(self, path: str | Path, drop_invalid: bool = True) -> Path:
        """Write the point cloud as ``x_mm,y_mm,z_mm`` CSV."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        points = self.to_points(drop_invalid=drop_invalid)
        with open(path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["x_mm", "y_mm", "z_mm"])
            writer.writerows(points)
        return path

    def save_ply(self, path: str | Path, binary: bool = True) -> Path:
        """Write the point cloud as a PLY file (CloudCompare/MeshLab readable).

        Args:
            path: Destination .ply path.
            binary: Write binary little-endian (much smaller/faster). ASCII
                is easier to eyeball for small test scans.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        points = self.to_points(drop_invalid=True).astype(np.float32)

        fmt = "binary_little_endian 1.0" if binary else "ascii 1.0"
        header = (
            "ply\n"
            f"format {fmt}\n"
            f"comment generated by laguna.scanner (Gocator)\n"
            f"element vertex {len(points)}\n"
            "property float x\n"
            "property float y\n"
            "property float z\n"
            "end_header\n"
        )
        with open(path, "wb") as f:
            f.write(header.encode("ascii"))
            if binary:
                f.write(points.tobytes())
            else:
                for x, y, z in points:
                    f.write(f"{x} {y} {z}\n".encode("ascii"))
        return path

    def save_npz(self, path: str | Path) -> Path:
        """Write the full grid (including NaNs) plus metadata as .npz.

        Preserves the grid structure that CSV/PLY flatten away — the right
        choice for reprocessing (e.g. re-deriving Y from a corrected velocity).
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            path,
            z_mm=self.z_mm,
            x_mm=self.x_mm,
            y_mm=self.y_mm,
            is_uniform=self.is_uniform,
            metadata=np.array([repr(self.metadata)], dtype=object),
        )
        return path

    def rescale_y(self, actual_speed_mm_s: float) -> "SurfaceScan":
        """Return a copy with Y rescaled for a corrected travel speed.

        Encoderless Y spacing is only as good as the travel speed the sensor
        was told (see docs/reference/gocator/GOCATOR_CONCEPTS.md §2c). If the
        gantry's true velocity is later measured to differ, this rescales the
        travel axis without a re-scan.

        Args:
            actual_speed_mm_s: Measured true velocity during the pass.

        Raises:
            ValueError: If the scan's metadata has no configured travel speed
                to scale relative to, or either speed is non-positive.
        """
        configured = self.metadata.get("travel_speed_mm_s")
        if not configured or configured <= 0 or actual_speed_mm_s <= 0:
            raise ValueError(
                "rescale_y() needs a positive 'travel_speed_mm_s' in metadata "
                f"and a positive actual speed; got configured={configured!r}, "
                f"actual={actual_speed_mm_s!r}"
            )
        factor = actual_speed_mm_s / configured
        metadata = dict(self.metadata)
        metadata.update(
            {
                "travel_speed_mm_s": actual_speed_mm_s,
                "y_rescaled_from_mm_s": configured,
                "y_rescale_factor": factor,
            }
        )
        return SurfaceScan(
            z_mm=self.z_mm.copy(),
            x_mm=self.x_mm.copy(),
            y_mm=self.y_mm * factor,
            metadata=metadata,
            is_uniform=self.is_uniform,
        )


# ----------------------------------------------------------------------
# Message -> SurfaceScan conversion
# ----------------------------------------------------------------------


def _scale(raw: np.ndarray, resolution_nm: int, offset_um: int) -> np.ndarray:
    """Apply Gocator's offset/resolution scaling, mapping invalids to NaN."""
    out = raw.astype(np.float64)
    out[raw == INVALID_RANGE_16BIT] = np.nan
    return offset_um * UM_TO_MM + resolution_nm * NM_TO_MM * out


def uniform_surface_to_scan(
    lib,
    msg,
    metadata: Optional[Dict[str, Any]] = None,
) -> SurfaceScan:
    """Convert a ``GoUniformSurfaceMsg`` handle into a :class:`SurfaceScan`.

    Args:
        lib: A :class:`laguna.scanner.gosdk.GoSdkLib`.
        msg: The message handle from ``GoDataSet_At``.
        metadata: Extra context to merge into the result's metadata.
    """
    import ctypes

    go = lib.go
    rows = int(go.GoUniformSurfaceMsg_Length(msg))
    cols = int(go.GoUniformSurfaceMsg_Width(msg))

    x_res = int(go.GoUniformSurfaceMsg_XResolution(msg))
    y_res = int(go.GoUniformSurfaceMsg_YResolution(msg))
    z_res = int(go.GoUniformSurfaceMsg_ZResolution(msg))
    x_off = int(go.GoUniformSurfaceMsg_XOffset(msg))
    y_off = int(go.GoUniformSurfaceMsg_YOffset(msg))
    z_off = int(go.GoUniformSurfaceMsg_ZOffset(msg))

    raw = np.empty((rows, cols), dtype=np.int16)
    for row in range(rows):
        row_ptr = go.GoUniformSurfaceMsg_RowAt(msg, row)
        if not row_ptr:
            # Defensive: a NULL row would otherwise fault inside numpy. Treat
            # the whole row as "no data" rather than losing the scan.
            raw[row, :] = INVALID_RANGE_16BIT
            continue
        # Copy immediately — the buffer belongs to the message, which the
        # caller destroys via GoDestroy once the dataset is released.
        raw[row, :] = np.ctypeslib.as_array(
            ctypes.cast(row_ptr, ctypes.POINTER(ctypes.c_int16)), shape=(cols,)
        )

    z_mm = _scale(raw, z_res, z_off)
    x_mm = x_off * UM_TO_MM + x_res * NM_TO_MM * np.arange(cols, dtype=np.float64)
    y_mm = y_off * UM_TO_MM + y_res * NM_TO_MM * np.arange(rows, dtype=np.float64)

    meta: Dict[str, Any] = {
        "message_type": "uniform_surface",
        "rows": rows,
        "cols": cols,
        "x_resolution_nm": x_res,
        "y_resolution_nm": y_res,
        "z_resolution_nm": z_res,
        "x_offset_um": x_off,
        "y_offset_um": y_off,
        "z_offset_um": z_off,
        "x_spacing_mm": x_res * NM_TO_MM,
        "y_spacing_mm": y_res * NM_TO_MM,
    }
    if metadata:
        meta.update(metadata)

    return SurfaceScan(z_mm=z_mm, x_mm=x_mm, y_mm=y_mm, metadata=meta, is_uniform=True)


def surface_point_cloud_to_scan(
    lib,
    msg,
    metadata: Optional[Dict[str, Any]] = None,
) -> SurfaceScan:
    """Convert a ``GoSurfacePointCloudMsg`` handle into a :class:`SurfaceScan`.

    Unlike the uniform surface, each cell carries its own x/y/z raw triple
    (an un-resampled surface), so X and Y come back as full 2-D arrays.
    """
    import ctypes

    from .gosdk import kPoint3d16s

    go = lib.go
    rows = int(go.GoSurfacePointCloudMsg_Length(msg))
    cols = int(go.GoSurfacePointCloudMsg_Width(msg))

    x_res = int(go.GoSurfacePointCloudMsg_XResolution(msg))
    y_res = int(go.GoSurfacePointCloudMsg_YResolution(msg))
    z_res = int(go.GoSurfacePointCloudMsg_ZResolution(msg))
    x_off = int(go.GoSurfacePointCloudMsg_XOffset(msg))
    y_off = int(go.GoSurfacePointCloudMsg_YOffset(msg))
    z_off = int(go.GoSurfacePointCloudMsg_ZOffset(msg))

    raw_x = np.empty((rows, cols), dtype=np.int16)
    raw_y = np.empty((rows, cols), dtype=np.int16)
    raw_z = np.empty((rows, cols), dtype=np.int16)

    # kPoint3d16s is three contiguous int16s, so a row of them views cleanly
    # as an (cols, 3) int16 array.
    for row in range(rows):
        row_ptr = go.GoSurfacePointCloudMsg_RowAt(msg, row)
        if not row_ptr:
            raw_x[row, :] = raw_y[row, :] = raw_z[row, :] = INVALID_RANGE_16BIT
            continue
        flat = np.ctypeslib.as_array(
            ctypes.cast(row_ptr, ctypes.POINTER(ctypes.c_int16)), shape=(cols * 3,)
        ).reshape(cols, 3)
        raw_x[row, :] = flat[:, 0]
        raw_y[row, :] = flat[:, 1]
        raw_z[row, :] = flat[:, 2]

    z_mm = _scale(raw_z, z_res, z_off)
    x_mm = _scale(raw_x, x_res, x_off)
    y_mm = _scale(raw_y, y_res, y_off)

    meta: Dict[str, Any] = {
        "message_type": "surface_point_cloud",
        "rows": rows,
        "cols": cols,
        "x_resolution_nm": x_res,
        "y_resolution_nm": y_res,
        "z_resolution_nm": z_res,
        "x_offset_um": x_off,
        "y_offset_um": y_off,
        "z_offset_um": z_off,
    }
    if metadata:
        meta.update(metadata)

    return SurfaceScan(z_mm=z_mm, x_mm=x_mm, y_mm=y_mm, metadata=meta, is_uniform=False)


# Keep kPoint3d16s importable from this module for callers that only touch
# the conversion layer.
__all__ = [
    "SurfaceScan",
    "uniform_surface_to_scan",
    "surface_point_cloud_to_scan",
    "INVALID_RANGE_16BIT",
]
